name: task_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.0-255.2.beta <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
#  cached_network_image: ^3.2.3
  loading_animation_widget: ^1.2.0+4
  youtube_player_flutter: ^8.1.2
  chewie: ^1.4.0
  video_player: ^2.5.1
  flick_video_player: ^0.5.0
  flutter: 
    sdk: flutter


dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/icons/
  uses-material-design: true

